language: cpp
script:
  - cd lib/ninja; ./configure.py --bootstrap; cd ../..
  - ./lib/ninja/ninja
  - ./build/automeka
  - ./build/bin/automeka/automeka
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - clang-3.8
sudo: false
