language: cpp
script:
  - cd lib/ninja; ./configure.py --bootstrap; cd ../..
  - ./lib/ninja/ninja
  - ./build/automeka
  - ./build/bin/automeka/automeka
compiler:
  - clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.8
    - llvm-3.8
    - llvm-3.8-dev
    - g++-4.9
    - gcc-4.9
    - cmake
    - ninja-build
    - libgl1-mesa-dev
    - libegl1-mesa-dev
cache: apt
